Lti autobind v2
UCL-INGI/INGInious pull request #424
Opened 2019-08-29 13:26 UTC by AugustH

- only active when plugin is loaded
- binds the lti-provided user to the course automatically

2019-09-08 17:33 UTC, GuillaumeDerval commented
It's not really a plugin as it tightly integrates in the core of INGInious. It seems possible to only keep some new hooks and do everything in the plugin. We think it would be better. We would gladly merge these new hooks :-)

2019-09-11 20:02 UTC, AugustH commented
new try: new hook + everything moved into plugin

2020-12-16 15:02 UTC, anthonygego requested changes
@GuillaumeDerval We finally never had your final thoughts on this.

2020-12-18 13:41 UTC, AugustH commented on inginious/frontend/plugins/ltiautobind/__init__.py
> +                        "bindings": {data["consumer_key"]: [lti_id, {}]},
Seems the core concept is ok - i will prepare a new patch shortly

2021-01-09 19:38 UTC, AugustH commented on inginious/frontend/plugins/ltiautobind/__init__.py
> +                        "bindings": {data["consumer_key"]: [lti_id, {}]},
I don't understand the "ltibindings" -- with it i get errors in frontend/user_manager.py line 333 which uses ``info["bindings"]``.

And if i want the user to be able to login the binding should include the id of the auth method (eg. the ldap plugin used).

2021-01-12 11:17 UTC, anthonygego commented on inginious/frontend/plugins/ltiautobind/__init__.py
> +                        "bindings": {data["consumer_key"]: [lti_id, {}]},
Indeed the bindings entry should exist and be an empty dictionary if the account does not exist. It is used for external authentication methods. So you need both ``bindings`` and ``ltibindings``.

2021-01-21 15:39 UTC, AugustH commented
created new version, see pull request #620

2022-01-10 08:56 UTC, Drumor commented
Closed as there is a new version of the PR

2022-01-10 08:56 UTC, closed without merging