research field in audience composition
UCL-INGI/INGInious pull request #712
Opened 2021-09-20 13:51 UTC by Drumor

add a research field in audience composition in place of a select element

2021-09-20 13:52 UTC, Drumor commented
linked #710

2021-09-21 09:10 UTC, anthonygego commented on inginious/frontend/templates/course_admin/audience_edit.html
> +                                        <!--<select id="registered_students" name="registered_students" class="form-control">
Please remove commented code here.

2021-09-23 07:09 UTC, anthonygego commented
You will have to update the minified js too.

2021-09-23 07:54 UTC, Drumor commented
Done

2021-10-07 13:58 UTC, anthonygego commented
Can you solve the conflicts (regenerating the minified js) ?

2021-10-21 09:14 UTC, Drumor commented
This one is ok to review/merge

2021-11-10 09:10 UTC, anthonygego requested changes
There is an improvement. However:
- the "registered students" tab actually lists all the available users.
- it is therefore possible to add an new student to register this way, but it won't be stored once the save button pushed.

=> Ideally, one box is enough. The unregistered student can be registered directly. Maybe we can warn the admin that the student is not part of the course students yet. This should simplify the js code as we are sure that users added in the interface are real INGInious users.

2021-11-24 15:12 UTC, Drumor commented
> There is an improvement. However:
> 
> * the "registered students" tab actually lists all the available users.
> * it is therefore possible to add an new student to register this way, but it won't be stored once the save button pushed.
> 
> => Ideally, one box is enough. The unregistered student can be registered directly. Maybe we can warn the admin that the student is not part of the course students yet. This should simplify the js code as we are sure that users added in the interface are real INGInious users.

In fact part of the logic was already done, so i simplified frontend to have only one box. Right now the admin is not aware that a student is registered or not to the course. If not, he is silently add to the course.

2021-12-16 11:49 UTC, anthonygego commented
> it is therefore possible to add an new student to register this way, but it won't be stored once the save button pushed.

This still does not work. How to reproduce :
- Add a student that is not registered to the course yet.
- Click on save, nothing changes.

2021-12-16 11:49 UTC, anthonygego commented on inginious/frontend/templates/course_admin/audience_edit.html
>                              <div role="tabpanel" class="card-body tab-pane active" id="tab_registered_student">
You can also remove the tabpanel as there is only one option left.

2021-12-17 10:03 UTC, Drumor commented
> > it is therefore possible to add an new student to register this way, but it won't be stored once the save button pushed.
> 
> This still does not work. How to reproduce :
> 
> * Add a student that is not registered to the course yet.
> * Click on save, nothing changes.

Seems ok to me no?

https://user-images.githubusercontent.com/13468630/146527043-018549ab-2d6d-486f-ad22-ab7184566fff.mp4

2022-01-05 10:19 UTC, anthonygego approved these changes

2022-01-05 10:20 UTC, anthonygego commented
LGTM

2022-01-05 10:20 UTC, merged