Refactor task dispensers to handle course-specific parameters
UCL-INGI/INGInious pull request #908
Opened 2023-01-16 12:16 UTC by anthonygego

This PR continues work begun in summer 2022 and makes task files re-usable as is accross different courses by moving all the course-related task parameters from the task files to the task dispenser settings, and is a pre-requisite to allow creating courses on top of the same task sets. 

I decided to parameterize the task settings options into different classes to allow a more fine-grain design of task dispenser as some options may be senseless for a given task dispenser (the basic example here is that group submission has no sense for CombinatoryTest that generates a different task list for each user). If/else to opt-in/out these configs was less an optimal choice as we could imagine designing a new task dispenser using the SectionList code but adding a new specific paramater. For instance, in adaptative testing, the pre-estimated difficulty of a question.

This PR is not feature-complete yet (no migration scripts) but mergeable to avoid a too big diff.

Done before this PR:

- [x] Moved weight to TOC-based task dispenser (#849)
- [x] Moved amount of stored submissions to task dispensers (#851)
- [x] Moved evaluation submission to task dispensers (#854)
- [x] Moved categories to task dispensers (#855)

Done in this PR:

- [x] Moved submission limitation to task dispenser
- [x] Moved group submission mode to task dispenser
- [x] Moved task accessibility to task dispenser
- [x] Improved TOC-based task dispenser structure and class definition to address performance issues
- [x] Refactored CombinatoryTest as an inherited class from TableOfContents
- [x] Re-implemented embedded contest plugin using TaskDispenser 
- [x] Make SectionsList task configuration fields modular to ease re-use of SectionsList for other dispensers

To do next (mandatory) :

- [ ] Remove retro-compatibility code and design a filesystem update tool next to the database one.

Nice to have :

- [ ] Improve task config UI to allow group-actions
- [ ] Ease the edition of dangling tasks, by listing them in another tab for instance, to better handle task dispensers whose behaviour is unpredictable with unaccessible tasks.
- [ ] Remove all pointers to the course from the task objects.

2023-03-10 09:36 UTC, Drumor requested changes

2023-03-14 08:50 UTC, anthonygego commented on inginious/frontend/task_dispensers/toc.py
> +        return set(reduce(concat, [self.get_categories(taskid) for taskid in taskids]))
Fixed in 2c587eb14a95b2c63fed8f376ab315c9e5da3085

2023-03-14 08:51 UTC, anthonygego commented on inginious/frontend/static/js/task_dispensers.js
>  function dispenser_structure_toc() {
Removed duplicates in 00637ab9510a73cf69d068bd195fa9ce9965d794

2023-03-17 10:33 UTC, Drumor approved these changes

2023-03-17 10:34 UTC, Drumor commented
LGTM, @nrybowski if you want a final check, i let you merge.

2023-03-23 15:07 UTC, merged